version: '3.8'

services:
  app:
    image: dianakuan/webgenai:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://wishgen-user:wishgen-password@postgres:5432/wishgen-db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: wishgen-db
      POSTGRES_USER: wishgen-user
      POSTGRES_PASSWORD: wishgen-password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
